name: Mobile-Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build-Android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine Version
        id: ver
        run: |
          if git describe --tags --exact-match >/dev/null 2>&1; then
            echo "version=$(git describe --tags --exact-match)" >> $GITHUB_OUTPUT
          else
            echo "version=dev-$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          fi

      - name: Install Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          ndk: 25.1.8937393
          cmake: 3.22.1

      - name: Install Haxelib Dependencies
        run: |
          haxelib install hxcpp
          haxelib install thx.core
          haxelib install thx.semver
          haxelib install lime
          haxelib install openfl
          haxelib install flixel 4.11
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.6.2
          haxelib install flixel-addons 3.3.0
          haxelib install flxanimate
          haxelib install json2object
          haxelib git polymod https://github.com/PabloelproxD210/Polymod.git
          haxelib git hscript https://github.com/T5mpler/hscript-dnb
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hmm
          haxelib run hmm install

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Patch hxcpp flags
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <xml>
            <section id="vars">
              <set name="HXCPP_CPP11" value="1"/>
            </section>
          </xml>' > ~/.hxcpp_config.xml

      - name: Build APK
        run: |
          haxelib run lime build android -D officialBuild -DONLY_ARMV7

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
